baseurl: '/'
permalink: pretty
title: 'Chrio'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"

footer:
  copyright_text: '© Copyright 2024 Chrio GmbH'

seo:
  meta_og_title: "Chrio"
  meta_og_type: "website"
  meta_og_url: "https://chrio.dev"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Entdecken Sie mit Chrio maßgeschneiderte KI-Lösungen und spezialisierte Dienstleistungen für Microsoft 365 Copilot, die auf die einzigartigen Anforderungen Ihres Unternehmens zugeschnitten sind. Unser Expertenteam ermöglicht es Ihrer Organisation, das volle Potenzial von fortschrittlicher KI und Microsoft 365 Copilot zu entfesseln, indem wir die Technologie nahtlos in Ihre Geschäftsprozesse integrieren und weiterentwickeln. Steigern Sie Effizienz, Innovation und Produktivität mit Chrios individuell angepassten Lösungen."
  meta_twitter_card: 
  meta_twitter_site: 
  meta_twitter_creator: 

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
